version: '3.8'

services:
  web:
    image: web:docker-compose
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    ports:
      - 8000:8000
    environment:
      REDIS_HOST: 'redis'
    tty: true
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis:5
    restart: always
    expose:
     - 6379
